{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "dedb251b-5c84-49b4-a899-a94b2d4c84bc",
   "metadata": {},
   "source": [
    "<div align=\"center\">\n",
    "  <h1>015 - Python Type Errors </h1>\n",
    "\n",
    "<sub>Author  :   Tharaka Mahabage   <br> <small> First Edition: April, 2024</small>\n",
    "</sub>\n",
    "</div>\n",
    "</div>\n",
    "\n",
    "[<<_14](../14_Higher_order_functions/14_higher_order_functions.ipynb) | [16 >>](../16_Python_date_time/16_python_datetime.ipynb)\n",
    "\n",
    "\n",
    "- [ðŸ“˜_15](#-day-15)\n",
    "  - [Python Error Types](#python-error-types)\n",
    "    - [SyntaxError](#syntaxerror)\n",
    "    - [NameError](#nameerror)\n",
    "    - [IndexError](#indexerror)\n",
    "    - [ModuleNotFoundError](#modulenotfounderror)\n",
    "    - [AttributeError](#attributeerror)\n",
    "    - [KeyError](#keyerror)\n",
    "    - [TypeError](#typeerror)\n",
    "    - [ImportError](#importerror)\n",
    "    - [ValueError](#valueerror)\n",
    "    - [ZeroDivisionError](#zerodivisionerror)\n",
    "  - [ðŸ’» Exercises:_15](#-exercises-day-15)\n",
    "\n",
    "\n",
    "\n",
    "## Python Error Types\n",
    "\n",
    "When we write code it is common that we make a typo or some other common error. If our code fails to run, the Python interpreter will display a message, containing feedback with information on where the problem occurs and the type of an error. It will also sometimes gives us suggestions on a possible fix. Understanding different types of errors in programming languages will help us to debug our code quickly and also it makes us better at what we do.\n",
    "\n",
    "Let us see the most common error types one by one. First let us open our Python interactive shell. Go to your you computer terminal and write 'python'. The python interactive shell will be opened.\n",
    "\n",
    "### SyntaxError\n",
    "\n",
    "**Example 1: SyntaxError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print 'hello world'\n",
    "  File \"<stdin>\", line 1\n",
    "    print 'hello world'\n",
    "                      ^\n",
    "SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?\n",
    ">>>\n",
    "```\n",
    "\n",
    "As you can see we made a syntax error because we forgot to enclose the string with parenthesis and Python already suggests the solution. Let us fix it.\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print 'hello world'\n",
    "  File \"<stdin>\", line 1\n",
    "    print 'hello world'\n",
    "                      ^\n",
    "SyntaxError: Missing parentheses in call to 'print'. Did you mean print('hello world')?\n",
    ">>> print('hello world')\n",
    "hello world\n",
    ">>>\n",
    "```\n",
    "\n",
    "The error was a _SyntaxError_. After the fix our code was executed without a hitch. Let see more error types.\n",
    "\n",
    "### NameError\n",
    "\n",
    "**Example 1: NameError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print(age)\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "NameError: name 'age' is not defined\n",
    ">>>\n",
    "```\n",
    "\n",
    "As you can see from the message above, name age is not defined. Yes, it is true that we did not define an age variable but we were trying to print it out as if we had had declared it. Now, lets fix this by declaring it and assigning with a value.\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> print(age)\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "NameError: name 'age' is not defined\n",
    ">>> age = 25\n",
    ">>> print(age)\n",
    "25\n",
    ">>>\n",
    "```\n",
    "\n",
    "The type of error was a _NameError_. We debugged the error by defining the variable name.\n",
    "\n",
    "### IndexError\n",
    "\n",
    "**Example 1: IndexError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> numbers = [1, 2, 3, 4, 5]\n",
    ">>> numbers[5]\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "IndexError: list index out of range\n",
    ">>>\n",
    "```\n",
    "\n",
    "In the example above, Python raised an _IndexError_, because the list has only indexes from 0 to 4 , so it was out of range.\n",
    "\n",
    "### ModuleNotFoundError\n",
    "\n",
    "**Example 1: ModuleNotFoundError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>>\n",
    "```\n",
    "\n",
    "In the example above, I added an extra s to math deliberately and _ModuleNotFoundError_ was raised. Lets fix it by removing the extra s from math.\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>> import math\n",
    ">>>\n",
    "```\n",
    "\n",
    "We fixed it, so let's use some of the functions from the math module.\n",
    "\n",
    "### AttributeError\n",
    "\n",
    "**Example 1: AttributeError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>> import math\n",
    ">>> math.PI\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "AttributeError: module 'math' has no attribute 'PI'\n",
    ">>>\n",
    "```\n",
    "\n",
    "As you can see, I made a mistake again! Instead of pi, I tried to call a PI function from maths module. It raised an attribute error, it means, that the function does not exist in the module. Lets fix it by changing from PI to pi.\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> import maths\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ModuleNotFoundError: No module named 'maths'\n",
    ">>> import math\n",
    ">>> math.PI\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "AttributeError: module 'math' has no attribute 'PI'\n",
    ">>> math.pi\n",
    "3.141592653589793\n",
    ">>>\n",
    "```\n",
    "\n",
    "Now, when we call pi from the math module we got the result.\n",
    "\n",
    "### KeyError\n",
    "\n",
    "**Example 1: KeyError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> users = {'name':'Asab', 'age':250, 'country':'Sri Lanka'}\n",
    ">>> users['name']\n",
    "'Asab'\n",
    ">>> users['county']\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "KeyError: 'county'\n",
    ">>>\n",
    "```\n",
    "\n",
    "As you can see, there was a typo in the key used to get the dictionary value. so, this is a key error and the fix is quite straight forward. Let's do this!\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> user = {'name':'Asab', 'age':250, 'country':'Sri Lanka'}\n",
    ">>> user['name']\n",
    "'Asab'\n",
    ">>> user['county']\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "KeyError: 'county'\n",
    ">>> user['country']\n",
    "'Sri Lanka'\n",
    ">>>\n",
    "```\n",
    "\n",
    "We debugged the error, our code ran and we got the value.\n",
    "\n",
    "### TypeError\n",
    "\n",
    "**Example 1: TypeError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> 4 + '3'\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "TypeError: unsupported operand type(s) for +: 'int' and 'str'\n",
    ">>>\n",
    "```\n",
    "\n",
    "In the example above, a TypeError is raised because we cannot add a number to a string. First solution would be to convert the string to int or float. Another solution would be converting the number to a string (the result then would be '43'). Let us follow the first fix.\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> 4 + '3'\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "TypeError: unsupported operand type(s) for +: 'int' and 'str'\n",
    ">>> 4 + int('3')\n",
    "7\n",
    ">>> 4 + float('3')\n",
    "7.0\n",
    ">>>\n",
    "```\n",
    "\n",
    "Error removed and we got the result we expected.\n",
    "\n",
    "### ImportError\n",
    "\n",
    "**Example 1: TypeError**\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> from math import power\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ImportError: cannot import name 'power' from 'math'\n",
    ">>>\n",
    "```\n",
    "\n",
    "There is no function called power in the math module, it goes with a different name: _pow_. Let's correct it:\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> from math import power\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ImportError: cannot import name 'power' from 'math'\n",
    ">>> from math import pow\n",
    ">>> pow(2,3)\n",
    "8.0\n",
    ">>>\n",
    "```\n",
    "\n",
    "### ValueError\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> int('12a')\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ValueError: invalid literal for int() with base 10: '12a'\n",
    ">>>\n",
    "```\n",
    "\n",
    "In this case we cannot change the given string to a number, because of the 'a' letter in it.\n",
    "\n",
    "### ZeroDivisionError\n",
    "\n",
    "```py\n",
    "Tharaka@Tharaka:~$ python\n",
    "Python 3.9.6 (default, Jun 28 2021, 15:26:21)\n",
    "[Clang 11.0.0 (clang-1100.0.33.8)] on darwin\n",
    "Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n",
    ">>> 1/0\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ZeroDivisionError: division by zero\n",
    ">>>\n",
    "```\n",
    "\n",
    "We cannot divide a number by zero.\n",
    "\n",
    "We have covered some of the python error types, if you want to check more about it check the python documentation about python error types.\n",
    "If you are good at reading the error types then you will be able to fix your bugs fast and you will also become a better programmer.\n",
    "\n",
    "ðŸŒ• You are excelling. You made it to half way to your way to greatness. Now do some exercises for your brain and for your muscle.\n",
    "\n",
    "## ðŸ’» Exercises:_15\n",
    "\n",
    "1. Open you python interactive shell and try all the examples covered in this section.\n",
    "\n",
    "ðŸŽ‰ CONGRATULATIONS ! ðŸŽ‰\n",
    "\n",
    "[<<_14](../14_Higher_order_functions/14_higher_order_functions.ipynb) | [16 >>](../16_Python_date_time/16_python_datetime.ipynb)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3658a19a-4b1d-43b8-a50d-724def9175cb",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e18aedf0-2081-431d-8977-3afc58176a1a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
